// Project gallery: eight neon scenes with generated artwork, and an accessible details dialog.
// Edit the `projects` array to change the cards. A repository link appears only where `repositoryUrl` is a real
// https address, and the dialog's links come from `caseStudy`, `repositoryUrl` and `section`.
// Built from the reference in Documents/Codex/2026-10-04/w/outputs/neon-project-gallery.
(function () {
  "use strict";

  var gallery = document.getElementById("pg-gallery");
  var dialog = document.getElementById("pg-details");
  if (!gallery || !dialog) return;

  // Where each project stands, as the case-study pages describe it
  var PUBLIC_REPO = "Public repository. Its tests target a demo or third-party site, not an employer system.";
  var CASE_STUDY = "Case study: a written-up approach, no public repository yet.";

  // color is an RGB triple used by the card and its artwork. effect is one of burst, circuit, grid, network.
  // modifier adds a scene variant (featured, wide). listOnCard shows the features on the card itself, and
  // tagsFirst puts the tags above the action row.
  var projects = [
    {
      title: "JARVIS — Advanced AI Assistant", color: [178, 255, 67], effect: "burst", modifier: "featured", icon: "menu",
      badge: "FEATURED PROJECT", featured: true, tagsFirst: true, action: "See the overview",
      description: "Personal AI assistant with plugins, voice, memory, screen context, and local tools. A central part of my workflow.",
      tags: ["AI Assistant", "Productivity", "Personal Tooling"],
      features: ["Modular plugins and local tools", "Voice interaction and persistent memory", "Screen context for everyday workflows"],
      section: "#jarvis", note: "Private repository, demo on request."
    },
    {
      title: "Playwright", color: [63, 218, 255], effect: "circuit", icon: "masks", listOnCard: true, action: "See the overview",
      description: "HTML and JUnit reports, traces on failure, mobile viewports, and GitHub Actions.",
      features: ["Playwright JavaScript", "HTML and JUnit reporters", "Traces and video on failure", "Mobile viewport checks"],
      caseStudy: "projects/playwright-weather-test.md", note: PUBLIC_REPO
    },
    {
      title: "Playwright", color: [65, 234, 243], effect: "circuit", icon: "masks", badge: "FEATURED", featured: true, action: "Case study",
      description: "HTML and JUnit reports, traces on failure, mobile viewports, and GitHub Actions.",
      tags: ["Playwright", "JavaScript"],
      features: ["Specs grouped by area with readable steps", "Trace collection and failure diagnostics", "Continuous integration with GitHub Actions"],
      caseStudy: "projects/playwright-weather-test.md", repositoryUrl: "https://github.com/PlamenTanevGit/Claude_Sinoptik_Autogenerated", note: PUBLIC_REPO
    },
    {
      title: "Selenium Java Framework", color: [255, 210, 51], effect: "grid", icon: "selenium", badge: "FEATURED", featured: true, action: "Case study",
      description: "Page Object Model with TestNG, data providers, reports, and parallel execution.",
      tags: ["Selenium", "Java", "POM"],
      features: ["Reusable page objects", "Parameterized tests with data providers", "Parallel execution and detailed reporting"],
      caseStudy: "projects/selenium-java-framework.md", repositoryUrl: "https://github.com/PlamenTanevGit/LamdaTestRefact", note: PUBLIC_REPO
    },
    {
      title: "Cypress Testing", color: [232, 63, 245], effect: "burst", icon: "cypress", badge: "CASE STUDY", action: "Case study",
      description: "Mocha and Chai, selector strategy, trade-offs and practice repository.",
      features: ["Stable selector strategies", "Mocha and Chai fundamentals", "Documented testing trade-offs"],
      caseStudy: "projects/cypress-testing.md", note: CASE_STUDY
    },
    {
      title: "API Testing", color: [104, 103, 255], effect: "network", icon: "braces", badge: "CASE STUDY", action: "Case study",
      description: "REST and SOAP approach with a worked test plan and Postman collection.",
      features: ["Positive and negative test scenarios", "Response and schema validation", "Authorisation and data checks"],
      caseStudy: "projects/api-testing.md", note: CASE_STUDY
    },
    {
      title: "Regression Suite", color: [255, 123, 36], effect: "burst", modifier: "wide", badge: "CASE STUDY", action: "Case study",
      description: "Smoke tests, critical flows, and risk-based selection, built from the layers above.",
      features: ["Fast smoke-test feedback", "Critical user journey coverage", "Risk-based regression selection"],
      caseStudy: "projects/regression-test-suite.md", note: CASE_STUDY
    },
    {
      title: "AI QA Workflows", color: [113, 250, 255], effect: "burst", modifier: "wide", badge: "CASE STUDY", action: "Case study",
      description: "Prompt and context files, review checklists, and where AI gets it wrong.",
      features: ["Reusable prompts and context files", "Human review checklists", "Documented AI limitations and failure modes"],
      caseStudy: "projects/ai-assisted-qa-workflows.md", note: CASE_STUDY
    }
  ];

  // 28 x 28 line icons for the card's icon tile
  var icons = {
    menu: '<path d="M5 7h18M5 12h18M5 17h18M5 22h18"/>',
    masks: '<path fill="#b95661" stroke="none" d="M2 7l13 2-2 12C6 24 2 17 2 7Z"/><path fill="#50b76b" stroke="none" d="m12 6 14-3c2 13-4 20-10 15Z"/><path stroke="#173b34" d="m16 9 2 1m3-2 2-1m-6 7q3 2 5-2"/><path stroke="#51232d" d="m5 11 2 1m2 1 2-1m-5 5 4 1"/>',
    selenium: '<path d="m14 5 4 4 7-7M4 7v17h20V13"/><path d="M12 13H8v4h4v4H8m8-4h6m-1-1c-5-4-7 7 1 4"/>',
    cypress: '<circle cx="14" cy="14" r="10"/><path d="M13 10c-8-4-8 12 0 8m2-8 3 7 3-7m-3 7-2 5"/>',
    braces: '<path d="M10 4C2 2 10 12 4 14c6 2-2 12 6 10M18 4c8-2 0 8 6 10-6 2 2 12-6 10"/>'
  };

  function escapeHtml(text) {
    return String(text).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; });
  }

  function tagList(items) {
    if (!items) return "";
    return '<div class="pg-tags">' + items.map(function (item) { return '<span class="pg-tag">' + escapeHtml(item) + "</span>"; }).join("") + "</div>";
  }

  function featureList(items) {
    return '<ul class="pg-features">' + items.map(function (item) { return "<li>" + escapeHtml(item) + "</li>"; }).join("") + "</ul>";
  }

  // ---------- Scenes ----------
  var canDialog = typeof dialog.showModal === "function";
  var previousFocus;

  projects.forEach(function (project, index) {
    var scene = document.createElement("div");
    scene.className = "pg-scene" + (project.modifier ? " pg-" + project.modifier : "");
    scene.style.setProperty("--accent", project.color.join(","));
    // These strings are authored in this file, not supplied by visitors.
    scene.innerHTML =
      '<canvas aria-hidden="true"></canvas><article class="pg-card" aria-labelledby="pg-project-' + index + '">' +
      (project.icon ? '<div class="pg-icon" aria-hidden="true"><svg viewBox="0 0 28 28">' + icons[project.icon] + "</svg></div>" : "") +
      (project.badge ? '<span class="pg-eyebrow' + (project.featured ? " pg-feature" : "") + '">' + escapeHtml(project.badge) + "</span>" : "") +
      '<h3 id="pg-project-' + index + '">' + escapeHtml(project.title) + "</h3><p>" + escapeHtml(project.description) + "</p>" +
      (project.listOnCard ? featureList(project.features) : "") +
      (project.tagsFirst ? tagList(project.tags) : "") +
      '<div class="pg-actions"><button type="button" aria-haspopup="dialog" aria-label="' + escapeHtml(project.action + ": " + project.title) + '">' + escapeHtml(project.action) + "</button></div>" +
      (project.tagsFirst ? "" : tagList(project.tags)) +
      "</article>";

    var button = scene.querySelector("button");
    if (project.repositoryUrl) {
      var url = new URL(project.repositoryUrl);
      if (url.protocol === "https:") {
        var link = document.createElement("a");
        link.href = url.href;
        link.textContent = "Repository";
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        scene.querySelector(".pg-actions").appendChild(link);
      }
    }
    if (canDialog) {
      button.addEventListener("click", function () { openDetails(project); });
    } else {
      button.hidden = true; // no dialog support: leave the card without a dead control
    }
    gallery.appendChild(scene);
  });

  // ---------- Details dialog ----------
  var detailTitle = document.getElementById("pg-detail-title");
  var detailText = document.getElementById("pg-detail-description");
  var detailFeatures = document.getElementById("pg-detail-features");
  var detailLinks = document.getElementById("pg-detail-links");
  var detailNote = document.getElementById("pg-detail-note");

  function replaceContent(parent, nodes) {
    parent.replaceChildren.apply(parent, nodes);
  }

  function detailLink(href, text, external) {
    var a = document.createElement("a");
    a.href = href;
    a.textContent = text;
    if (external) { a.target = "_blank"; a.rel = "noopener noreferrer"; }
    return a;
  }

  function openDetails(project) {
    previousFocus = document.activeElement;
    var links = [];
    if (project.caseStudy) links.push(detailLink(project.caseStudy, "Read the case study"));
    if (project.repositoryUrl && /^https:/.test(project.repositoryUrl)) links.push(detailLink(project.repositoryUrl, "View the repository", true));
    if (project.section) {
      var here = detailLink(project.section, "See it on this page");
      // The visitor is leaving for another part of the page, so do not pull focus back to the card button
      here.addEventListener("click", function () { previousFocus = null; dialog.close(); });
      links.push(here);
    }
    detailTitle.textContent = project.title;
    detailText.textContent = project.description;
    replaceContent(detailFeatures, project.features.map(function (text) {
      var li = document.createElement("li");
      li.textContent = text;
      return li;
    }));
    replaceContent(detailLinks, links);
    detailNote.textContent = project.note || "";
    dialog.showModal();
  }

  dialog.querySelector(".pg-close").addEventListener("click", function () { dialog.close(); });
  // A click on the backdrop lands on the dialog element itself, outside its box
  dialog.addEventListener("click", function (event) {
    var r = dialog.getBoundingClientRect();
    if (event.target === dialog && (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom)) dialog.close();
  });
  dialog.addEventListener("close", function () { if (previousFocus && previousFocus.focus) previousFocus.focus(); });

  // ---------- Artwork ----------
  // Deterministic canvas art: each scene keeps its own pattern on resize. There is no animation loop, which
  // saves battery and respects reduced motion. Do not reorder the random() calls, they define the picture.
  function random(seed) {
    return function () {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      return seed / 4294967296;
    };
  }

  function paint(scene, index) {
    var canvas = scene.querySelector("canvas");
    var ctx = canvas.getContext("2d");
    if (!ctx) return;
    var w = scene.clientWidth, h = scene.clientHeight, dpr = Math.min(window.devicePixelRatio || 1, 2);
    canvas.width = Math.round(w * dpr);
    canvas.height = Math.round(h * dpr);
    ctx.scale(dpr, dpr);
    var p = projects[index], rng = random(index * 12345 + 782), cx = w / 2, cy = h / 2, r = Math.max(w, h) * 0.7;
    var color = function (alpha) { return "rgba(" + p.color.join(",") + "," + alpha + ")"; };

    var aura = ctx.createRadialGradient(cx, cy, 10, cx, cy, r);
    aura.addColorStop(0, color(0.85)); aura.addColorStop(0.3, color(0.27)); aura.addColorStop(0.7, color(0.045)); aura.addColorStop(1, color(0));
    ctx.fillStyle = aura;
    ctx.fillRect(0, 0, w, h);
    ctx.globalCompositeOperation = "screen";

    if (p.effect === "burst" || p.effect === "grid") {
      for (var i = 0; i < 380; i++) {
        var angle = rng() * Math.PI * 2, start = r * (0.12 + rng() * 0.15), end = r * (0.4 + rng() * 0.7), spread = 0.001 + rng() * 0.023;
        var x = cx + Math.cos(angle) * end, y = cy + Math.sin(angle) * end;
        var ray = ctx.createLinearGradient(cx, cy, x, y);
        ray.addColorStop(0, color(0)); ray.addColorStop(0.32, color(0.18 + rng() * 0.28)); ray.addColorStop(0.62, color(0.08)); ray.addColorStop(1, color(0));
        ctx.fillStyle = ray;
        ctx.beginPath();
        ctx.moveTo(cx + Math.cos(angle) * start, cy + Math.sin(angle) * start);
        ctx.lineTo(cx + Math.cos(angle - spread) * end, cy + Math.sin(angle - spread) * end);
        ctx.lineTo(cx + Math.cos(angle + spread) * end, cy + Math.sin(angle + spread) * end);
        ctx.fill();
      }
    }

    if (p.effect === "circuit") {
      ctx.lineWidth = 1.4;
      for (var side = 0; side < 4; side++) {
        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate(side * Math.PI / 2);
        for (var j = 0; j < 15; j++) {
          var px = (j - 7) * w * 0.024, py = h * 0.13, len = h * (0.24 + rng() * 0.24), bend = (j - 7) * 6;
          ctx.strokeStyle = color(0.2 + rng() * 0.4); ctx.shadowColor = color(0.8); ctx.shadowBlur = 7;
          ctx.beginPath();
          ctx.moveTo(px, py); ctx.lineTo(px, py + 35); ctx.lineTo(px + bend, py + 35 + Math.abs(bend)); ctx.lineTo(px + bend, len);
          ctx.stroke();
          if (j % 3 === 0) { ctx.beginPath(); ctx.arc(px + bend, len, 2.5, 0, Math.PI * 2); ctx.stroke(); }
        }
        ctx.restore();
      }
    }

    if (p.effect === "grid") {
      ctx.strokeStyle = color(0.32);
      ctx.lineWidth = 1;
      for (var g = -10; g <= 10; g++) {
        ctx.beginPath();
        ctx.moveTo(cx, cy); ctx.lineTo(cx + g * w * 0.18, 0);
        ctx.moveTo(cx, cy); ctx.lineTo(cx + g * w * 0.18, h);
        ctx.moveTo(cx, cy); ctx.lineTo(0, cy + g * h * 0.18);
        ctx.moveTo(cx, cy); ctx.lineTo(w, cy + g * h * 0.18);
        ctx.stroke();
      }
      for (var s = 0.15; s < 1.6; s *= 1.23) ctx.strokeRect(cx - w * s / 2, cy - h * s / 2, w * s, h * s);
    }

    if (p.effect === "network") {
      var points = [];
      for (var n = 0; n < 48; n++) points.push({ x: rng() * w, y: rng() * h });
      points.forEach(function (a, k) {
        points.slice(k + 1).forEach(function (b) {
          if (Math.hypot(a.x - b.x, a.y - b.y) < w * 0.24) {
            ctx.strokeStyle = color(0.25);
            ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
          }
        });
        ctx.fillStyle = color(0.85);
        ctx.beginPath(); ctx.arc(a.x, a.y, 2 + rng() * 6, 0, Math.PI * 2); ctx.fill();
      });
    }

    // Lens flares, and small light particles around the card
    var flares = p.effect === "circuit" ? [[cx - w * 0.22, cy], [cx + w * 0.22, cy - h * 0.13]] : [[cx, cy - h * 0.23], [cx - w * 0.25, cy + h * 0.1], [cx + w * 0.24, cy]];
    flares.forEach(function (f) {
      var glow = ctx.createRadialGradient(f[0], f[1], 0, f[0], f[1], w * 0.23);
      glow.addColorStop(0, "rgba(255,255,235,.95)"); glow.addColorStop(0.06, color(0.95)); glow.addColorStop(0.3, color(0.27)); glow.addColorStop(1, color(0));
      ctx.fillStyle = glow;
      ctx.fillRect(f[0] - w * 0.23, f[1] - w * 0.23, w * 0.46, w * 0.46);
    });
    for (var m = 0; m < 100; m++) {
      var a = rng() * Math.PI * 2, d = r * (0.2 + rng() * 0.5);
      ctx.fillStyle = color(rng() * 0.5);
      ctx.fillRect(cx + Math.cos(a) * d, cy + Math.sin(a) * d, 1 + rng() * 2, 1 + rng() * 3);
    }
    ctx.globalCompositeOperation = "source-over";
  }

  // The section sits far down a long page and every canvas is large, so a scene is painted only when it is about
  // to be seen. After that it is repainted on resize.
  var scenes = Array.prototype.slice.call(gallery.querySelectorAll(".pg-scene"));
  scenes.forEach(function (scene, index) { scene.dataset.index = index; });

  function paintScene(scene) {
    paint(scene, Number(scene.dataset.index));
    scene.dataset.painted = "yes";
  }

  if ("IntersectionObserver" in window) {
    var watcher = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        watcher.unobserve(entry.target);
        paintScene(entry.target);
      });
    }, { rootMargin: "800px 0px" });
    scenes.forEach(function (scene) { watcher.observe(scene); });
  } else {
    scenes.forEach(paintScene);
  }

  var pending;
  var firstResize = true;
  function repaint() {
    cancelAnimationFrame(pending);
    pending = requestAnimationFrame(function () {
      scenes.forEach(function (scene) { if (scene.dataset.painted) paintScene(scene); });
    });
  }
  if ("ResizeObserver" in window) {
    new ResizeObserver(function () {
      // the first call only reports the starting size, which the scenes have already been painted at
      if (firstResize) { firstResize = false; return; }
      repaint();
    }).observe(gallery);
  }
})();
